#!/usr/bin/env bash
# vim:set expandtab shiftwidth=4 filetype=bash:
# SPDX-License-Identifier: GPL-3.0-or-later

#
#
# ~chewygumxx/dotfiles.git
# ::: :/.chezmoiscripts/run_wezterm-terminfo
#
#

#
# Updates wezterm terminfo definition
#

# ---------
# Variable
# ---------

verbose="${CHEZMOISCRIPT_WEZTERM_TERMINFO_VERBOSE:-${CHEZMOISCRIPT_VERBOSE:-${CHEZMOI_VERBOSE:-${VERBOSE:-0}}}}"

# Assumes wezterm unstable release
# https://wezterm.org/config/lua/config/term.html
url="${CHEZMOISCRIPT_WEZTERM_TERMINFO_URL:-https://raw.githubusercontent.com/wezterm/wezterm/main/termwiz/data/wezterm.terminfo}"

dest="${CHEZMOISCRIPT_WEZTERM_TERMINFO_DEST:-${TERMINFO:-${TERMINFO_DIRS:+${TERMINFO_DIRS%%:*}}}}"
if [[ -z "$dest" ]] || [[ -d "$dest" && ! -w "$dest" ]]; then
    dest="${CHEZMOI_DEST_DIR:-$HOME}/.terminfo"
fi

if command -v realpath >/dev/null 2>&1; then
    __this_file="$(realpath "${BASH_SOURCE[0]}")"
else
    __this_file="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)/$(basename -- "${BASH_SOURCE[0]}")"
fi

last_success="${CHEZMOI_CACHE_DIR:-${XDG_CACHE_HOME:-${CHEZMOI_DEST_DIR:-$HOME}/.cache}/chezmoi}/${__this_file##*/}.last_success"
dependencies=( curl tic sha256sum )


# --------
# Helpers
# --------

__log () {
    local level="INFO"
    case "$1" in
        INFO|NOTICE|WARN|ERROR|FATAL) level="$1"; shift ;;
    esac
    [[ $level == INFO ]] && (( verbose )) && return

    printf "%s: [%s] %s\n" "${__this_file##*/}" "$level" "$*" >&2
}

cleanup=()
trap 'rm -f -- "${cleanup[@]}"' EXIT

if errfile="$(mktemp "${TMPDIR:-/tmp}/${__this_file##*/}_errfile.XXXXXXX" 2>&1)"; then :; else
    exit_code=$?
    __log FATAL "mktemp exited with code $exit_code"
    __log FATAL "$errfile"
    exit "$exit_code"
fi
cleanup+=("$errfile")
__guard() {
    if "$@" 2>"$errfile"; then :; else
        exit_code=$?
        __log FATAL "$1 exited with code ${exit_code}"
        __log FATAL "Exec: $*"
        __log FATAL "stderr: $(<"$errfile")"
        exit "$exit_code"
    fi
}

__validate_dependencies() {
    local dep dependency_fail=0
    for dep in "${dependencies[@]}"; do
        if ! command -v "$dep" &>/dev/null; then
            __log FATAL "Dependency not found in PATH: $dep"
            dependency_fail=1
        fi
    done
    (( dependency_fail )) && exit 127
} 

# -----------
# Generate
# -----------

__generate_terminfo() {
    #shellcheck disable=SC2155
    local tmp="$(__guard mktemp "${TMPDIR:-/tmp}/${__this_file##*/}_curl.XXXXXXX")"
    cleanup+=("$tmp")
    __guard curl \
        --silent \
        --show-error \
        --fail-with-body \
        --retry 3 \
        --retry-delay 2 \
        --retry-all-errors \
        --connect-timeout 5 \
        --max-time 15 \
        --output "$tmp" \
        -- "$url"
    
    __log NOTICE "Regenerating to: $dest"
    __guard mkdir -p -- "$dest"
    __guard tic -x -o "$dest" -- "$tmp"

    __guard mkdir -p -- "${last_success%/*}"
    if printf "%s\n" "$generation_info" 2>"$errfile" >"$last_success"; then :; else
        exit_code=$?
        __log FATAL "Failed to write generation info to: $last_success"
        __log FATAL "printf redirection exited $exit_code"
        __log FATAL "Exec: printf \"%s\n\" \"\$generation_info\" > \"$last_success\""
        __log FATAL "stderr: $(<"$errfile")"
        exit "$exit_code"
    fi
    __log NOTICE "Regeneration successful"

    if  [[ "${TERM_PROGRAM:-}" == "WezTerm" ]]; then
        if [[ "${TERMINFO:-}" == "$dest" || :"${TERMINFO_DIRS:-}": == *:"$dest":* ]]; then
            return
        else
            __log WARN "Destination directory not found in WezTerm TERMINFO or TERMINFO_DIRS"
            __log WARN "See: https://wezterm.org/config/lua/config/term.html"
        fi
    fi

    __log NOTICE "Ensure the following directory is included in WezTerm TERMINFO or TERMINFO_DIRS: $dest"
}


# -----
# Main
# -----

if ! command -v wezterm &>/dev/null; then
    __log INFO "Execution superfluous, WezTerm not found."
    exit 0
fi

__validate_dependencies

generation_info="wezterm_version=$(__guard wezterm --version)"
generation_info+=$'\n'"terminfo_url=$url"
generation_info+=$'\n'"dest=$dest"
generation_info+=$'\n'"script_hash=$(__guard sha256sum <"$__this_file")"

if [[ ! -f "$last_success" ]] || [[ "$generation_info" != "$(<"$last_success")" ]]; then
    __generate_terminfo
fi
