# vim:set expandtab shiftwidth=4 filetype=yaml:
# SPDX-License-Identifier: GPL-3.0-only

#
#
# ~chewygumxx/dotfiles.git
# ::: :/home/dot_config/gh/config.yml
#
#

#
# GitHub CLI
#
# Manual:                https://cli.github.com/manual/gh
# Reference:             https://cli.github.com/manual/gh_help_reference
# Configuration:         https://cli.github.com/manula/gh_config
#                        or `gh config --help`
# Environment Variables: https://cli.github.com/manual/gh_help_environment
#                        or `gh environment --help`
#


# Schema Version
version: 1

# Environment Variables take precedence ( DO_NOT_TRACK=true & GH_TELEMETRY=false )
telemetry: disabled


# --------
# Aliases
# --------

aliases:
    co:  pr checkout
    pub: gist create --public
    sec: gist create


# -----------
# Essentials
# -----------

editor:                     # Fallback to EDITOR/VISUAL
pager:                      # Fallback to PAGER ('cat' to disable)
browser: firefox --new-tab  # Fallback to BROWSER.
git_protocol: ssh           # http/ssh
http_unix_socket:
api_host:


# ----------
# Interface
# ----------

spinner:               enabled  # Animated Loading Indicator
prompt:                enabled  # Interactive Prompt
color_labels:          enabled  # Truecolor

accessible_colors:    disabled  # 4-bit
accessible_prompter:  disabled  # Accessibility
prefer_editor_prompt: disabled  # Editor-based Interactive Prompting
