# vim:set expandtab shiftwidth=4 filetype=yaml:
# SPDX-License-Identifier: GPL-3.0-only

#
#
# ~chewygumxx/dotfiles.git
# ::: :/.github/header_ignore.yaml
#
#

ignore:
    - /LICENSE
    - /.chezmoiroot
    - /.chezmoiversion
    - "symlink_*"
    - "*.json"
    - "*.gif"
    - "*.png"
    - "*.svg"
    - "*.jpg"
    - "*.jpeg"
    - "*.tiff"
    - "*.webm"
    - "*.mp4"
    - "*.mkv"
    - "*.ogg"
    - "*.flac"

