# vim: expandtab:shiftwidth=4

# 
# 
# ~/.local/share/chezmoi/.chezmoiexternal.toml
# 
# 

# [".local/bin/eza"]
#     type = "archive-file"
#     url = {{ gitHubLatestReleaseAssetURL "eza-community/eza" "eza_x86_64-unknown-linux-gnu.tar.gz" | quote }}
#     executable = true
#     path = "./eza"
