#!/bin/sh
# vim:set expandtab shiftwidth=4 filetype=sh:

#
#
# ~chewygumxx/dotfiles.git
# ::: :/run_onchange_wezterm-terminfo
#
#

set -eu

url="https://raw.githubusercontent.com/wezterm/wezterm/main/termwiz/data/wezterm.terminfo"
dest="${XDG_DATA_HOME:-${CHEZMOI_DEST_DIR:-$HOME}/.local/share}/terminfo"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

curl --fail --silent --show-error \
    --connect-timeout 5 --max-time 15 \
    -o "$tmp" "$url"

mkdir -p "$dest"
tic -x -o "$dest" "$tmp"
