#!/usr/bin/env sh

#
#
# ~/.local/share/chezmoi/run_onchange_weaterm_terminfo
#
#

#
# Depends on curl
#

tempfile=$(mktemp) \
  && curl -o $tempfile https://raw.githubusercontent.com/wezterm/wezterm/main/termwiz/data/wezterm.terminfo \
  && tic -x -o ~/.local/share/terminfo $tempfile \
  && rm $tempfile

