#!/bin/sh
# vim:set expandtab shiftwidth=4 filetype=sh:

#
#
# ~chewygumxx/dotfiles.git
# ::: :/run_onchange_wezterm-terminfo
#
#

url="https://raw.githubusercontent.com/wezterm/wezterm/main/termwiz/data/wezterm.terminfo"
dest="${XDG_DATA_HOME:-${CHEZMOI_DEST_DIR:-$HOME}/.local/share}/terminfo"

tmp="$(mktemp)" \
    && curl -o "$tmp" "$url" \
    && tic -x -o "$dest" "$tmp"

[ -e "$tmp" ] && rm -f "$tmp"
