#!/bin/sh

#
#
# ~chewygumxx/dotfiles.git:/run_onchange_wezterm_terminfo.sh
#
#

#
# Depends on curl
#

tempfile=$(mktemp) \
  && curl -o $tempfile https://raw.githubusercontent.com/wezterm/wezterm/main/termwiz/data/wezterm.terminfo \
  && tic -x -o ~/.local/share/terminfo $tempfile \
  && rm $tempfile

