# vim: expandtab:shiftwidth=4

#
#
# /etc/zsh/zshenv
#
# 

# 
# ** This file executes at the start of *EVERY* zsh shell
#

[[ -z "$XDG_DATA_HOME"   ]] && XDG_DATA_HOME="$HOME/.local/share"
[[ -z "$XDG_STATE_HOME"  ]] && XDG_STATE_HOME="$HOME/.local/state"
[[ -z "$XDG_CACHE_HOME"  ]] && XDG_CACHE_HOME="$HOME/.local/cache"
[[ -z "$XDG_CONFIG_HOME" ]] && XDG_CONFIG_HOME="$HOME/.config"
[[ -z "$XDG_RUNTIME_DIR" ]] && XDG_RUNTIME_DIR="/run/user/$(id -u)"

export XDG_DATA_HOME
export XDG_STATE_HOME
export XDG_CACHE_HOME
export XDG_CONFIG_HOME
export XDG_RUNTIME_DIR


[[ -d "$XDG_CONFIG_HOME/zsh" ]] && ZDOTDIR="$XDG_CONFIG_HOME/zsh"
#export ZDOTDIR # Given this is /etc/zshenv, this is almost never necessary.
