# vim:set expandtab shiftwidth=4 filetype=toml:
# SPDX-License-Identifier: GPL-3.0-only
#
#
# ~chewygumxx/dotfiles.git
# ::: :/home/dot_config/lazysql/config.toml
#
#

[application]
DefaultPageSize = 300
DisableSidebar = false

[[database]]
Name = 'inventory'
URL = 'file:inventory.sqlite?loc=auto'
Provider = 'sqlite3'
Username = ''
Password = ''
Hostname = ''
Port = ''
DBName = ''
URLParams = ''
Commands = []
