#!/usr/bin/env zsh
# vim: expandtab:shiftwidth=4

# 
# 
# ~/.config/@_sysroot_etc/script/sudoers_d
# 
# 


local this_file="$0"
function error_exit () { print -u2 "${this_file}: $1"; [[ ${#} -eq 2 ]] && exit $2; }

USERCONF_ETC="$XDG_CONFIG_HOME/@_sysroot_etc"
[[ "$(pwd)" -eq "$USERCONF_ETC" ]] || error_exit "Filenames must be relative to $USERCONF_ETC" 1

function install () {
    local sudoers_src="./src/sudoers.d"
    [[ -d "$sudoers_src" ]] || error_exit "Failed to find $sudoers_src" 1

    echo "Validating sudoers.d files"
    setopt xtrace
    for file in $(ls --quote-name "$sudoers_src"); do
        visudo --check --file="$sudoers_src/$file" 2>&1
        [[ $? -ne 0 ]] || error_exit "Failed non-strict visudo check" 1
    done
    unsetopt xtrace

    echo -e "Check the above for \e[1;91mANYTHING potentially intolerable\e[0m,"
    echo "this could be painful otherwise."
    select strictreply in "Yes" "No"; do
        local relaxedreply=${strictreply:-$REPLY}
        case $relaxedreply in
            Yes | yes | y ) break ;;
            No  | no  | n )
                error_exit "Sudoers.d installation responsibly cancelled" 0
                ;;
        esac
    done
    unset strictreply

    echo "Attempting installation of sudoers.d files"
    setopt xtrace
    for file in $(ls --quote-name "$sudoers_src"); do
        sudo install --mode=0440 "$sudoers_src/$file" /etc/sudoers.d
    done
    unsetopt xtrace
    unset file

    echo "Executing final visudo strict check"
    setopt xtrace
    sudo visudo --check --strict 2>&1
    unsetopt xtrace
}
