# vim: expandtab:shiftwidth=4

# 
# 
# ~/.config/zsh/zlogin
# 
# 

# Test if zprofile is sourced
#echo "$(date)" >> /tmp/zlogin.txt

path+=(
    "$HOME/.local/bin"
)

#export LC_ALL="C.UTF-8"
export EDITOR="nvim"
export VISUAL="$EDITOR"
export PAGER="less"
export TERMCMD="wezterm"
export BROWSER="firefox"

# echo "$(date)" >> /tmp/zlogin.txt
