# vim: expandtab:tabstop=4:shiftwidth=4:textwidth=80:
# vim: foldmethod=marker

#
#
# ~/.config/zsh/zshrc
#
#

#  
#  /etc/zshenv contains:
#      export ZDOTDIR="${XDG_CONFIG_HOME:-"$HOME/.config"}/zsh"
#  ~/.config/environment.d/env.conf contains:
#      export ZDOTDIR="${XDG_CONFIG_HOME:-"$HOME/.config"}/zsh"
#
#  Symlinked: $ZDOTDIR/.zshrc -> this
#

# Shell Interactivity Check
[[ -o interactive ]] || return

zshrcs=( "$zsh_dirs[conf]/rc/"{,util/}*.rc.zsh )
zshrcs=(
    ${(M)zshrcs:#*completion*}
    ${(M)zshrcs:#*function*}
    ${zshrcs:#*(completion|function)*}
)

for source in $zshrcs; do
    source "$source"
done

zle_highlight=('paste:none')

setopt re_match_pcre

# Allow `# comment`. Good for copying and pasting commands from web
setopt interactive_comments 

# Resolve symbolic links to their true physical path when changing
# directories. `cd ..` afterward will not return to the parent directory of
# the original symbolic link. Also infers option 'chase_dots'.
setopt chase_links

#
# *** Post-Startup
#

# Splash
#print-quote

#zprof
