# vim: expandtab:tabstop=4:shiftwidth=4:textwidth=80:
# vim: foldmethod=marker

#
#
# ~/.config/zsh/zshrc
#
#

#  
#  /etc/zshenv contains:
#      export ZDOTDIR="${XDG_CONFIG_HOME:-"$HOME/.config"}/zsh"
#  ~/.config/environment.d/env.conf contains:
#      export ZDOTDIR="${XDG_CONFIG_HOME:-"$HOME/.config"}/zsh"
#
#  Symlinked: $ZDOTDIR/.zshrc -> this
#

# Shell Interactivity Check
[[ -o interactive ]] || return

# {{{ Zsh Directories
    typeset -A zsh_home
    zsh_home=(
        [cache]="$XDG_CACHE_HOME/zsh"
        [state]="$XDG_STATE_HOME/zsh"
        [site_func]="$XDG_DATA_HOME/zsh/site-functions"
    )

    for DIR in ${(v)zsh_home}; do
        [[ -d $DIR ]] || mkdir -p $DIR
    done

    fpath+=($zsh_home[site_func])
# }}}

zle_highlight=('paste:none')

# {{{ Options
    # Allow `# comment`. Good for copying and pasting commands from web
    setopt interactive_comments 

    # Resolve symbolic links to their true physical path when changing
    # directories. `cd ..` afterward will not return to the parent directory of
    # the original symbolic link. Also infers option 'chase_dots'.
    setopt chase_links

    # {{{ History
        HISTFILE="${XDG_STATE_HOME:-"$HOME/.local/state"}/zsh/history"

        # SAVEHIST > HISTSIZE
        HISTSIZE=20000000
        SAVEHIST=21000000
        
        # Upon shell exit: Append to history file      
        # Records both time invoked and execution time
        setopt inc_append_history_time  

        # Despite Zsh documentation of the INC_APPEND_HISTORY_TIME        
        # inferring a following setopt EXTENDED_HISTORY is redundant, it                                  
        # seems (somehow?) it does need to be setopt-ed for timestamping.
        setopt extended_history         
                                        
        # Upon SHELL exit: Append to history file, rather than rewrite
       #setopt append_history
        
        # Share a live, common history among all active shells
       #setopt share_history
        
        # TODO(@chewygumxx):
        #   I don't understand why I'm interested in atuin's history database
        #   I have absolutely no use for it 
    # }}}
# }}}

# {{{ Sources
    __native_source_list=(
        "alias"
        "completion"
        "function"
        "prompt"
        #"zsh-vi-mode"
    )
    for native in $__native_source_list; do
        source $ZDOTDIR/native/${native}.zshrc
    done
    unset __native_source_list

    __cmd_source_list=(
        "bat"
        "chezmoi"
        "eza"
        "fzf"
        "gtrash"
        "tldr"
        "zoxide"
    )
    for cmd in $__cmd_source_list; do
        source $ZDOTDIR/command/${cmd}.zshrc
    done
    unset __cmd_source_list

    ZSH_PLUGIN_DIR="/usr/share/zsh/plugins"
    __zsh_plugin_list=(
        "fast-syntax-highlighting"
       #"zsh-autocomplete"
        "zsh-vi-mode"
    )
    for plugin in $__zsh_plugin_list; do
        source $ZDOTDIR/plugin/${plugin}.zshrc
    done
    unset __zsh_plugin_list
# }}}

autoload edit-command-line
zle -N edit-command-line
bindkey '^e' edit-command-line

# {{{ luarocks
    # Exports environment variables
    #   LUA_PATH
    #   LUA_CPATH
    #   PATH (appends to)
    #
    # TODO(@chewygumxx):
    #   Disabled, replaced with a source file that is updated via luarocks
    #   version switch hook TODO(@chewygumxx)
    #eval $(luarocks path --bin)
    [ -s "$XDG_CONFIG_HOME/luarocks/env.sh" ] &&
        source "$XDG_CONFIG_HOME/luarocks/env.sh"
# }}}
# {{{ nvm
    # Node Version Manager
    # --no-use    Load nvm only when called
    [ -s "$NVM_DIR/nvm.sh" ] &&
        source "$NVM_DIR/nvm.sh"  --no-use     
# }}}

#
# *** Post-Startup
#

print-quote

