# vim: expandtab:tabstop=4:shiftwidth=4:textwidth=80:
# vim: foldmethod=marker

#
#
# ~/.config/zsh/zshrc
#
#

#  
#  ~/.config/environment.d/env.conf contains:
#      export ZDOTDIR=/home/chewygumxx/.config/zsh
#
#  Symlinked: ./.zshrc -> this
#

# Shell Interactivity Check
[[ $- != *i* ]] && return     

# {{{ Zsh Directories
    typeset -A zsh_home
    zsh_home=(
        [cache]="$XDG_CACHE_HOME/zsh"
        [state]="$XDG_STATE_HOME/zsh"
        [site_func]="$XDG_DATA_HOME/zsh/site-functions"
    )

    for DIR in ${(v)zsh_home}; do
        [[ -d $DIR ]] || mkdir -p $DIR
    done

    fpath+=($zsh_home[site_func])
# }}}

# {{{ Options
    setopt interactive_comments
    zle_highlight=('paste:none')

    # {{{ History
        HISTFILE="$zsh_home[state]/history"

        # SAVEHIST > HISTSIZE
        HISTSIZE=20000000
        SAVEHIST=21000000
        
        # Upon shell exit: Append to history file      
        # Records both time invoked and execution time
        setopt inc_append_history_time  
                                        
        # Despite Zsh documentation of the INC_APPEND_HISTORY_TIME        
        # inferring a following setopt EXTENDED_HISTORY is redundant, it                                  
        # seems (somehow?) it does need to be setopt-ed for timestamping.
        setopt extended_history         
                                        
        # Upon SHELL exit: Append to history file, rather than rewrite
       #setopt append_history
        
        # Share a live, common history among all active shells
       #setopt share_history
        
        # TODO(@chewygumxx):
        #   I don't understand why I'm interested in atuin's history database
        #   I have absolutely no use for it 
    # }}}
# }}}

# {{{ Sources
    source $ZDOTDIR/prompt.zsh
    source $ZDOTDIR/alias.zsh
    source $ZDOTDIR/func.zsh

    CMD_ASSIST_LIST=(
        "chezmoi"
        "eza"
        "gtrash"
        "firefox"
    )
    for CMD_ASSIST in $CMD_ASSIST_LIST; do
        source $ZDOTDIR/command/${CMD_ASSIST}.source.zsh
    done

    PLUGIN_LIST=(
        "fast-syntax-highlighting"
       #"zsh-autocomplete"
        "plugin-zsh-vi-mode"
    )
    for PLUGIN in $PLUGIN_LIST; do
        source $ZDOTDIR/plugin/${PLUGIN}.source.zsh
    done
# }}}

# {{{ Auto Completion
    autoload -Uz compinit
    setopt list_types

    zstyle ':completion:*' use-cache on
    zstyle ':completion:*' cache-path "$zsh_home[cache]/compcache"

    zstyle ':completion:*' menu select
    zstyle ':completion:*' group-name ''
    zstyle ':completion:*' list-dirs-first true
    zstyle ':completion:*:*:*:*:descriptions' format '%F{green}-- %d --%f'
    zstyle ':completion:*:*:-command-:*:*' group-order aliases builtins functions commands

    # {{{ ZLS_COLORS
        typeset -T ZLS_COLORS zls_colors :
        zls_colors=(
            "di=$color[bold];$color[blue]"      # Directory
            "fi=$color[none]"                   # Ordinary file
            "ex=$color[bold];$color[green]"     # Executable

            "so=$color[bold];$color[red]"       # Socket
            "pi=$color[yellow]"                 # Named pipe (FIFO)
            "bd=$color[bold];$color[yellow]"    # Block device
            "cd=$color[bold];$color[yellow]"    # Character device

            "ln=$color[italic];$color[cyan]"    # Symlink
            "or=$color[italic];$color[blink];$color[reverse]$color[red]"   # Broken symlink

            "tc=$color[faint]$color[magenta]"   # Filetype trailing character
        )

        # Archive
        for ext in "7z" "gz" "rar" "tar" "zip"; do
            zls_colors+=("*.$ext=$color[red]")
        done

        # Audio
        for ext in "flac" "m4a" "mka" "mp2" "mp3" "ogg"; do
            zls_colors+=("*.$ext=$color[italic];$color[magenta]")
        done

        # Document
        for ext in "pdf" "doc" "docx"; do
            zls_colors+=("*.$ext=$color[cyan]")
        done

        # Image
        for ext in "avif" "bmp" "gif" "ico" "jfif" "jpg" "jpeg" "png" "svg" "tif" "tiff" "webp" "xcf"; do
            zls_colors+=("*.$ext=$color[magenta]")
        done

        # Source
        for ext in "css" "js" "lua" "py" "rs" "sql" "styl" "tsx" "zsh"; do
            zls_colors+=("*.$ext=$color[yellow]")
        done

        # Video
        for ext in "avi" "m4v" "mkv" "mov" "mp4" "mpeg" "mpg" "webm"; do
            zls_colors+=("*.$ext=$color[bold];$color[magenta]")
        done
    # }}}
    zstyle ":completion:*" list-colors $ZLS_COLORS

    zmodload zsh/complist
    bindkey -M menuselect '^h' vi-backward-char
    bindkey -M menuselect '^k' vi-up-line-or-history
    bindkey -M menuselect '^j' vi-down-line-or-history
    bindkey -M menuselect '^l' vi-forward-char

    _comp_options+=(globdots)

    # Save extended_glob state
    [[ -o extended_glob ]]; local_extglob=$?
        setopt extended_glob

        COMPDUMP="$zsh_home[cache]/zcompdump"
        # Glob explanation:
        #   N      Return an empty list if nothing found, instead of an error
        #   mh-24  Return files less than 24 hours old.
        if [[ -n $COMPDUMP(Nmh-24) ]]; then
            compinit -C -d  $COMPDUMP
        else
            compinit -d     $COMPDUMP
        fi

    # Resume extended_glob state
    (( local_extglob )) && unsetopt extended_glob
# }}}

# {{{ fzf
    # The ubiquitous fuzzy finder, invoked here for
    #   CTRL-R
    #       Search command history
    #   CTRL-T
    #       Search recursively from CWD
    if command -v fzf &>/dev/null; then
        eval "$(fzf --zsh)"
    fi
# }}}
# {{{ zoxide
    # Fuzzy frecency directory jumper
    #   According to repository README, must be invoked *after* compinit.
    #   https://github.com/ajeetdsouza/zoxide#:~:text=Zsh-,Add,compinit,-%2E
    #
    if command -v zoxide &>/dev/null; then
        eval "$(zoxide init --cmd cd zsh)"
    fi
# }}}

# {{{ luarocks
    # Exports environment variables
    #   LUA_PATH
    #   LUA_CPATH
    #   PATH (appends to)
    #
    # TODO(@chewygumxx):
    #   Disabled, replaced with a source file that is updated via luarocks
    #   version switch hook TODO(@chewygumxx)
    #eval $(luarocks path --bin)
    [ -s "$XDG_CONFIG_HOME/luarocks/env.sh" ] &&
        source "$XDG_CONFIG_HOME/luarocks/env.sh"
# }}}
# {{{ nvm
    # Node Version Manager
    # --no-use    Load nvm only when called
    [ -s "$NVM_DIR/nvm.sh" ] &&
        source "$NVM_DIR/nvm.sh"  --no-use     
# }}}

source /home/chewygum/.config/broot/launcher/bash/br

#
# *** Post-Startup
#

print-quote

