# vim:noexpandtab:tabstop=4:shiftwidth=4:textwidth=80

#
#
# ~/.config/hypr/hyprpaper.conf
#
#

$wallpaper = /home/chewygum/ref/image/top/wallpaper/current_eDP-1

wallpaper {
	monitor = eDP-1
	path	= $wallpaper
	fit_mode= cover
}

# Fuck your quote defacing my wallpaper
splash = false

#preload		= $bg_dir/current_eDP-1
#wallpaper	= eDP-1, $bg_dir/current_eDP-1

#preload		= $bg_dir/current_HDMI-1
#wallpaper	= HDMI-1, $bg_dir/current_HDMI-1
