# vim:set expandtab shiftwidth=4 filetype=toml:
# SPDX-License-Identifier: GPL-3.0-only

#
#
# ~chewygumxx/dotfiles.git
# ::: :/home/.chezmoiexternals/chezmoi-apply-xattr.toml
#
#

{{ if or (lookPath "xattr") (lookPath "setfattr") }}

[".local/bin/chezmoi-apply-xattr"]
    type = "archive-file"
    path = "chezmoi-apply-xattr"
    executable = true
    refreshPeriod = "168h"
    url = {{ gitHubLatestReleaseAssetURL "chewygumxx/chezmoi-apply-xattr" "chezmoi-apply-xattr-v*.tar.gz" | quote }}

{{ end }}
