# vim:set expandtab shiftwidth=4 filetype=conf:
# SPDX-License-Identifier: GPL-3.0-only

#
#
# ~chewygumxx/dotfiles.git
# ::: :/home/dot_config/environment.d/ssh.conf
#
#

SSH_AUTH_SOCK=${XDG_RUNTIME_DIR}/ssh-agent-protonpass.socket
