#!/usr/bin/env zsh
# vim:set expandtab shiftwidth=4 filetype=zsh:
# SPDX-License-Identifier: GPL-3.0-only

#
#
# ~chewygumxx/dotfiles.git
# ::: :/root/etc/zsh/zshenv
#
#


#
# ** This file executes at the start of *EVERY* zsh shell
#


# ----------------
# XDG Directories
# ----------------

: ${XDG_DATA_HOME:="$HOME/.local/share"}
: ${XDG_STATE_HOME:="$HOME/.local/state"}
: ${XDG_CACHE_HOME:="$HOME/.local/cache"}
: ${XDG_CONFIG_HOME:="$HOME/.config"}
: ${XDG_RUNTIME_DIR:="/run/user/$(id -u)"}

export XDG_{DATA,STATE,CACHE,CONFIG}_HOME XDG_RUNTIME_DIR

# --------
# ZDOTDIR
# --------
# The most efficacious and idiosyncratic method of creating a new custom zsh
# shell from template is to inline prepend the `zsh -i` invocation with
# environment variables.
#
# The most powerful being ZDOTDIR

: ${ZDOTDIR="$XDG_CONFIG_HOME/zsh"}
