# vim: expandtab:shiftwidth=4

# 
# 
# ~chewygumxx/dotfiles.git
# ::: :/dot_config/environment.d/command.conf
# 
# 

PATH="${PATH}:${HOME}/.local/bin"
PAGER="less -r"
EDITOR="nvim"
VISUAL="${EDITOR:-"nvim"}"
BROWSER=firefox
TERMCMD=wezterm
