# vim:

#
#
# ~/.config/tealdeer/config.toml
#
#

#
# Must be TOML 1.0 spec. No JSON-esque multiline tables.
#

[display]
show_title = false
compact    = false
use_pager  = false

[style.description]
foreground = { ansi = 11 } # Light Yellow
underline  = false
bold       = false
italic     = false

[style.command_name]
foreground = "green"
underline  = false
bold       = false
italic     = false

[style.example_text]
foreground = "blue"
underline  = false
bold       = false
italic     = false

[style.example_code]
foreground = "magenta"
underline  = false
bold       = false
italic     = false

[style.example_variable]
foreground = { ansi = 13 } # Light Magenta
underline  = false
bold       = false
italic     = false

[search]
languages = [ "en" ]
platform  = [ "current", "common", "all" ]

[updates]
auto_update = true
auto_update_interval_hours = 168
download_languages = [ "en" ]

[directories]
# Does not perform variable expansion. 
# If not /absolute/path/to/dir, path relative to $XDG_CONFIG_HOME/tealdeer
# Solution: Symlink $XDG_CONFIG_HOME/tealdeer/pages to
#           ../../alternative/specified/directory
# or just:
custom_pages_dir = "../../doc/tealdeer"
