[style.description]
foreground = { ansi = 7 }
underline = false
bold = false
italic = false

[style.command_name]
foreground = "green"
underline = false
bold = false
italic = false

[style.example_text]
foreground = "blue"
underline = false
bold = false
italic = false

[style.example_code]
foreground = "magenta"
underline = false
bold = false
italic = false

[style.example_variable]
underline = false
bold = false
italic = false

[display]
compact = false
use_pager = false

[updates]
auto_update = true
auto_update_interval_hours = 168

[directories]
