# vim:set expandtab shiftwidth=4 filetype=conf:
# SPDX-License-Identifier: GPL-3.0-only
#
#
# ~chewygumxx/dotfiles.git
# ::: :/home/dot_config/xdg-desktop-portal/hyprland-portals.conf
#
#

[preferred]
default = hyprland;kde
org.freedesktop.impl.portal.FileChooser=termfilechooser
