#!/usr/bin/env zsh
# vim:set expandtab shiftwidth=4 filetype=zsh:
# SPDX-License-Identifier: GPL-3.0-only

#
#
# ~chewygumxx/dotfiles.git
# ::: :/root/etc/zshrc
#
#


# Handles nonexistent commands.
#if [[ -x "${PREFIX}/libexec/termux/command-not-found" ]]; then
#	command_not_found_handler() {
#		"${PREFIX}/libexec/termux/command-not-found" "$1"
#
#       # I'm giving up
#       #
#       # I've been here for two hours on an LSD trip.
#       # Having to repeatedly overwrite this very fucking file so
#       # my otherwise adequately justifiable persistent undotree
#       # Neovim configuration doesn't reciprocally backfire in
#       # response to my regularly scheduled termux-nvim input
#       # bitchfit.
#       #
#       # I need a better means of keyboard.
#
#       # NOTE: Foremostly, I need to cultivate self-compassion
#       # to substitute this descructive self-languishing.
#    }
#fi
