# vim: expandtab:shiftwidth=4:textwidth=80

#
#
# ~/.termux/colors/chewygumxx.colors.properties
#
#

#background=#03030b
background=#000000

foreground=#9493de

cursor=#cad6ff

color0=#000000
color1=#dc143c
color2=#0fe192
color3=#c6c45e
color4=#5f95fa
color5=#7408ff
color6=#7fc5df
color7=#cad6ff

color8=#4e4189
color9=#e3365e
color10=#0fff72
color11=#ffca44
#color12=#7fc5ff
color12=#5f95fa
color13=#a430ff
color14=#8be9fd
color15=#e8e0ff
