# vim: expandtab:shiftwidth=4:textwidth=78

#
#
# termux:~/.termux/termux.properties
#
#

#
# Execute `termux-reload-settings` for changes to take effect.
# Some properties require app process restart.
# https://wiki.termux.com/wiki/Terminal_Settings
#

#
# ** General
#

default-working-directory = /data/data/com.termux/files/home
disable-terminal-session-change-toast = true
hide-soft-keyboard-on-startup = false

# Allow external applications to execute arbirary commands within Termux.
# Major security issue.
# Enabled for:
# - MiXplorer
# - Tasker
allow-external-apps = true

# Keyboard toggle button to enable or disable software keyboard rather than 
# showing/hiding it.
#soft-keyboard-toggle-behaviour = enable/disable

# Adjust terminal scrollback buffer. Max is 50000. May affect performance.
terminal-transcript-rows = 5000

# Use volume keys for adjusting volume rather than extra keys functionality.
#volume-keys = volume

#
# ** Fullscreen mode
#

# Uncomment to let Termux start in full screen mode.
#fullscreen = true

# Uncomment to attempt workaround layout issues when running in full screen
# mode.
#use-fullscreen-workaround = true

#
# ** Cursor
#

# Values: 0, 100 - 2000
terminal-cursor-blink-rate = 2000

# Options: block, bar, underline
terminal-cursor-style = bar

#
# ** Extra keys
#

# Symbols set to employ for illustrating keys.
# Options: default, arrows-only, arrows-all, all, none 
extra-keys-style = arrows-all

# Force capitalize all text in extra keys row button labels.
extra-keys-text-all-caps = false

extra-keys = [[ 'ESC',    '~',   '/',    '-', 'BACKSLASH',   '|' ], \
              [ 'TAB', 'CTRL', 'ALT', 'HOME',       'END', 'DEL' ]]

#extra-keys = [[ 'ESC',    '~',   '/',    '-', 'BACKSLASH',   '|' ], \
#              [ 'TAB', 'CTRL', 'ALT', 'HOME',       'END', 'DEL' ]]

# Default extra-key configuration
#extra-keys = [[ESC, TAB, CTRL, ALT, {key: '-', popup: '|'}, DOWN, UP]]

# Additional popup keys (swipe up from an extra key)
#extra-keys = [[ \
#  {key: ESC,   popup: {macro: "CTRL f d",    display: "tmux exit"}}, \
#  {key: CTRL,  popup: {macro: "CTRL f BKSP", display: "tmux ←"   }}, \
#  {key: ALT,   popup: {macro: "CTRL f TAB",  display: "tmux →"   }}, \
#  {key: TAB,   popup: {macro: "ALT a",       display: A-a}}, \
#  {key: LEFT,  popup: HOME}, \
#  {key: DOWN,  popup: PGDN}, \
#  {key: UP,    popup: PGUP}, \
#  {key: RIGHT, popup: END}, \
#  {macro: "ALT j", display: A-j, popup: {macro: "ALT g", display: A-g}}, \
#  {key: KEYBOARD,  popup: {macro: "CTRL d", display: exit}} \
#]]

# Advanced popup key usage specialised for Vim-like editor navigation.
#extra-keys = [ \
#  [ \
#    { key: ESC,  popup: { macro: ":q\n", display: "QuickExit" } }, \
#    { key: '/',  popup: '\\\\' }, \
#    { key: '-',  popup: '_'    }, \
#    { key: HOME, popup: { macro: "CTRL HOME", display: "Top" } }, \
#    { key: UP,   popup: { macro: "CTRL UP",   display: "UP"  } }, \
#    { key: END,  popup: { macro: "CTRL END",  display: "End" } }, \
#    { key: ":",  popup: ";" }, \
#    { key: "(",  popup: "{" }  \
#  ], \
#  [ \
#    { key: TAB,   popup: { macro: ":wq\n", display: "Write And Exit" } }, \
#    { key: CTRL,  popup: { macro: ":w\n",  display: "Write" } }, \
#           ALT,   \
#    { key: LEFT,  popup: { macro: "CTRL LEFT",  display: "Left"   } }, \
#    { key: DOWN,  popup: { macro: "CTRL DOWN",  display: "Bottom" } }, \
#    { key: RIGHT, popup: { macro: "CTRL RIGHT", display: "Right"  } }, \
#    { key: "#",   popup: "$" }, \
#    { key: ")",   popup: "}" } \
#  ] \
#]

#
# ** Colors/themes
#

# Force black colors for drawer and dialogs
use-black-ui = true

#
# ** Hardware Keyboard Shortcuts
#

#disable-hardware-keyboard-shortcuts = true

#shortcut.create-session   = ctrl + t
#shortcut.next-session     = ctrl + 2
#shortcut.previous-session = ctrl + 1
#shortcut.rename-session   = ctrl + n

#
# ** Bell key
#

# Options: vibrate, beep, ignore
bell-character = ignore

#
# ** Back key
#

# Options: escape, back
# back-key=back

#
# ** Keyboard Issue Workarounds
#

# Letters might not appear until enter is pressed on Samsung devices
#enforce-char-based-input = true

# ctrl+space (for marking text in emacs) does not work on some devices
#ctrl-space-workaround = true

#
# ** Terminal Margin
#

# Left/Right
terminal-margin-horizontal=3

# Top/Bottom
terminal-margin-vertical=0
