# vim: expandtab:shiftwidth=4:filetype=toml:

#
#
# ~chewygumxx/dotfiles.git 
# ::: :/dot_config/chezmoi.termux.toml
#
#

#
# Termux-specific chezmoi configuration linked to from ~/.config/chezmoi/chezmoi.toml
#


# Ignore Termux file permissions when adding to source state.
umask = 0o22
