#!/usr/bin/env zsh
# vim: expandtab:shiftwidth=4

# 
# 
# ~/.config/zsh/func/freload
# 
# 

#
# Reloads zsh function file from fpath
#

emulate -L zsh

local func
for func in "$@"; do
    unset -f -- "$func" 2>/dev/null
    autoload -Uz +X -- "$func"
done
