# vim:set expandtab shiftwidth=4 filetype=yaml foldlevel=5:
# SPDX-License-Identifier: GPL-3.0-only

#
#
# ~chewygumxx/dotfiles.git
# ::: :/.github/workflows/apply-repo-metadata-jsonc.yaml
#
#

name: Apply repository metadata (JSONC)
on:
    push:
        paths:
            - .repo-metadata.jsonc
    workflow_dispatch: {}

permissions:
    contents: read

jobs:
    apply:
        runs-on: ubuntu-latest
        steps:
            - name: Mint App Installation Token
              id: app-token
              uses: actions/create-github-app-token@v3
              with:
                  # `client-id` is correct. actionlint falsely flags `client-id`
                  # as incorrect and erroneously suggests `app-id.
                  client-id: ${{    vars.METADATA_APP_CLIENT_ID   }}
                  private-key: ${{ secrets.METADATA_APP_PRIVATE_KEY }}
                  permission-administration: write

            - name: Checkout
              uses: actions/checkout@v5

            - name: Apply Metadata
              uses: chewygumxx/apply-repo-metadata-jsonc@v2
              with:
                  metadata_path: .repo-metadata.jsonc
                  token: ${{ steps.app-token.outputs.token }}
